#!/usr/bin/perl
foreach $name ( @ARGV )  {
    $newname = $name;
    $newname =~ tr/!/-/;

    $newname =~ s/[^a-zA-z\\-\\.\/\-]\W//g;

    $newname =~ s/%25/%/g;
    $newname =~ s/%20/-/g;
    $newname =~ s/%5B/[/g;
    $newname =~ s/%5D/]/g;
    $newname =~ s/%2B/+/g;
    $newname =~ s/%3F/?/g;
    $newname =~ s/%3D/=/g;
    $newname =~ s/%26/&/g;
    $newname =~ s/%40/@/g;

    $newname =~ s/_/_/g;
    $newname =~ s/ /-/g;
    $newname =~ s/,//g;
    $newname =~ s/'//g;
    $newname =~ s/\(//g;
    $newname =~ s/\)//g;
    $newname =~ s/\±//g;
    $newname =~ s/\§//g;
    $newname =~ s/\!//g;
    $newname =~ s/\@//g;
    $newname =~ s/\£//g;
    $newname =~ s/\$//g;
    $newname =~ s/\%//g;
    $newname =~ s/\^//g;
    $newname =~ s/\&//g;
    $newname =~ s/\*//g;
    $newname =~ s/\+//g;
    $newname =~ s/\=//g;
    $newname =~ s/\{//g;
    $newname =~ s/\}//g;
    $newname =~ s/\[//g;
    $newname =~ s/\]//g;
    $newname =~ s/\"//g;
    $newname =~ s/\|//g;
    $newname =~ s/\\//g;
#    $newname =~ s/\///g; # Causes . to be added at the begining of the filename
    $newname =~ s/\<//g;
    $newname =~ s/\>//g;
    $newname =~ s/\?//g;
    $newname =~ s/\~//g;
    $newname =~ s/\`//g;

#    print "$name becomes $newname\n";
#    print "$newname\n";

   rename ($name, temp);
   rename (temp, $newname);
}